---
sudo: required
services:
  - docker

branches:
  only:
    - master

before_install:
  - source .gitter-env
  - sudo apt-get update -qq
  - sudo apt install python3-pip -y && alias pip=pip3
  - sudo apt-get install sshpass # sshpass is needed for Travis instance to connect to EC2 instance
  - echo ${ANSIBLE_VAULT_PASSPHRASE} > ec2-deployment/roles/setup/vars/ansible-vault-pw

install:
  # Install Ansible on Travis instance
  - sudo apt-get update -qq
  - sudo pip install ansible
  - sudo pip install ansible-lint

script:
  # run tests
  # Check docker-compose build runs successfully
  # - cd docker-deployment/build
  # - docker-compose build
  # Check the role/playbook's syntax
  - ansible-playbook -i ec2-deployment/inventory.yml ec2-deployment/site.yml --syntax-check
  # Run ansible playbook
  - ansible-playbook -i ec2-deployment/inventory.yml --vault-id ec2-deployment/roles/setup/vars/ansible-vault-pw ec2-deployment/site.yml -vv #--skip-tags dockerhub_push

after_success:
  - echo "Successfully deployed app to AWS EC2 instance with Ansible and pushed images to Dockerhub."


