---
sudo: required
services:
  - docker

# language: python
# python: "3.6"

# env:
#   - DOCKER_COMPOSE_VERSION=1.4.2

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt install python3-pip -y
  - alias pip=pip3
  - sudo apt-get install sshpass
  - echo ${ANSIBLE_VAULT_PASSPHRASE} > github-deployment/roles/setup/vars/ansible-vault-pw



install:
  # Install Ansible.
  - sudo apt-get update -qq
  # - sudo apt-get upgrade -y
  - sudo pip install ansible
  - sudo pip install ansible-lint
  # - sudo rm /usr/local/bin/docker-compose
  # - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  # - chmod +x docker-compose
  # - sudo mv docker-compose /usr/local/bin

script:
  - docker-compose build
  # Check the role/playbook's syntax.
  - ansible-playbook -i github-deployment/inventory.yml github-deployment/site.yml --syntax-check
  # Run ansible playbook
  - ansible-playbook -i github-deployment/inventory.yml --vault-id github-deployment/roles/setup/vars/ansible-vault-pw github-deployment/site.yml -vvv --skip-tags dockerhub_push

after_success:
  - Successfully deployed app to AWS EC2 instance with Ansible.
  - Pushing images to Dockerhub...

before_deploy:
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}

deploy:
  provider: script
  script: docker-compose push 
  # ${DOCKER_USERNAME}/${DOCKERHUB_IMAGE}
  on:
    branch: master


