# Travis to automate the following tasks:
# Run tests
# Run docker deploy commands with makefile?
# Run Ansible script

# Ansible script to automate the following tasks:
# access ec2 instance
# install dependencies, docker, conda, etc.
# git clone repo
# run tests
# build images and run containers
# push images to dockerhub

---
sudo: required
services:
  - docker

branches:
  only:
    - master

before_install:
  - source .gitter-env
  - sudo apt-get update -qq
  - sudo apt install python3-pip -y && alias pip=pip3
  - sudo apt-get install sshpass # sshpass is needed for Travis instance to connect to EC2 instance
  - echo ${ANSIBLE_VAULT_PASSPHRASE} > ec2-deployment/roles/setup/vars/ansible-vault-pw

install:
  # Install Ansible on Travis instance
  - sudo apt-get update -qq
  - sudo pip install ansible
  - sudo pip install ansible-lint

script:
  # Check docker-compose build runs successfully
  # - cd docker-deployment/build
  # - docker-compose build
  # Ansible deployment
  - make ansible-all
  # Equivalent of the following commands
  # - make ansible-checksyntax
  # - make ansible-instance-setup
  # - make ansible-deploy-build
  # - make ansible-instance-cleanup
  # - make ansible-deploy-prod

after_success:
  - echo "Successfully deployed app to AWS EC2 instance with Ansible and pushed images to Dockerhub."


