version: "3"
services:
  app:
    container_name: myapp
    restart: always
    image: gbournique/ansible-app:latest
    build: ./app
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  client:
    container_name: myclient
    restart: always
    image: gbournique/ansible-client:latest
    build: ./client
    ports:
      - "3000:3000"
    links:
      - app
  mongo:
    container_name: mymongo
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"