---
# This playbook sets up whole stack.
# https://medium.com/@rossbulat/ansible-automating-app-build-and-deployment-from-a-github-repository-7d613985f686

# Run ansible :
# ansible-playbook -i github-deployment/inventory.yml --vault-id user@~/.ssh/ansible-vault-pw github-deployment/site.yml -vv
# Run ansible with ansible-vault-pw included in the repo (+ my_aws_ssh_key.pem in the repo)
# ansible-playbook -i github-deployment/inventory.yml --vault-id github-deployment/roles/setup/vars/ansible-vault-pw github-deployment/site.yml -vv
# /!\ Make sure to delete ssh key and ansible-vault-pw if public repo\
# ssh to ubuntu VM: 
# ssh -i ~/.ssh/my_aws_key.pem ubuntu@ec2-15-188-54-132.eu-west-3.compute.amazonaws.com
# ssh ubuntu@ec2-15-188-54-132.eu-west-3.compute.amazonaws.com
# https://comtechies.com/password-authentication-aws-ec2.html
# brew install http://git.io/sshpass.rb


- name: Configurations to "remote_server" host
  gather_facts: true
  hosts: remote_server
  remote_user: "{{ ANSIBLE_USER }}" # Remote user
  become: yes
  roles:
    - setup