# This playbook contains docker actions that will be run on "remote" host.

- name: Stop running containers
  shell: docker stop $(docker ps -a -q) 2>/dev/null
  register: cmdln
  failed_when: "cmdln.rc == 2"
  tags:
    - docker-cleanup

- name: Remove all stopped containers
  shell: docker rm $(docker ps -a -q) 2>/dev/null
  register: cmdln
  failed_when: "cmdln.rc == 2"
  tags:
    - docker-cleanup

- name: Docker prune all
  shell: docker system prune -a -f
  tags:
    - docker-cleanup