# This playbook contains docker actions that will be run on "remote" host.

- name: Destroying build environment and Removing dangling images...
  shell: cd {{ REPO_LOCAL_PATH }} && make docker-clean
  register: cmdln
  failed_when: "cmdln.rc == 2"
  tags:
    - build

- name: Building images and starting services...
  shell: cd {{ REPO_LOCAL_PATH }} && make docker-build-images
  register: cmdln
  failed_when: "cmdln.rc == 2"
  tags:
    - build