# This playbook contains docker actions that will be run on "remote" host.

- name: docker-compose up
  docker_compose:
    build: yes
    project_src: "{{ repo_folder }}"
    pull: yes
    state: present

- name: run make all for deployment and push to Dockerhub
  shell: make all
  register: cmdln
  failed_when: "cmdln.rc == 2"