# This playbook contains docker actions that will be run on "remote" host.

- name: Starting services...
  shell: cd {{ REPO_LOCAL_PATH }} && make docker-start-services
  register: cmdln
  failed_when: "cmdln.rc == 2"
  tags:
    - start-services