# This playbook contains docker actions that will be run on "remote" host.
# automate acceptance tests once all services are running 

- name: Curl app front-end
  shell: if [ $(curl 0.0.0.0:80 | wc -w) -gt 0 ]; then echo "front-end running"; else exit 2; fi
  register: cmdln
  failed_when: "cmdln.rc == 2"
  tags:
    - acceptance-tests

- name: Curl app back-end
  shell: if [ $(curl 0.0.0.0:4000 | wc -w) -gt 0 ]; then echo "back-end running"; else exit 2; fi
  register: cmdln
  failed_when: "cmdln.rc == 2"
  tags:
    - acceptance-tests