
- name: "Logging in to Docker registry..."
  shell: cd {{ repo_folder }} && make login
  register: cmdln
  failed_when: "cmdln.rc == 2"

- name: Tagging release images with tags latest...
  shell: cd {{ repo_folder }} && make tag-latest
  register: cmdln
  failed_when: "cmdln.rc == 2"

- name: "Publishing release images to Docker Registry..."
  shell: cd {{ repo_folder }} && make publish
  register: cmdln
  failed_when: "cmdln.rc == 2"

- name: Destroying build environment and Removing dangling images...
  shell: cd {{ repo_folder }} && make clean
  register: cmdln
  failed_when: "cmdln.rc == 2"