
- name: "Logging in to Docker registry..."
  shell: cd {{ REPO_LOCAL_PATH }} && make docker-login/{{ DOCKER_PASSWORD }}
  register: cmdln
  failed_when: "cmdln.rc == 2"
  tags:
    - push-registry

- name: Tagging release images with tags latest...
  shell: cd {{ REPO_LOCAL_PATH }} && make docker-tag/latest
  register: cmdln
  failed_when: "cmdln.rc == 2"
  tags:
    - push-registry

- name: "Publishing release images to Docker Registry..."
  shell: cd {{ REPO_LOCAL_PATH }} && make docker-publish
  register: cmdln
  failed_when: "cmdln.rc == 2"
  tags:
    - push-registry

- name: Destroying build environment and Removing dangling images...
  shell: cd {{ REPO_LOCAL_PATH }} && make docker-clean
  register: cmdln
  failed_when: "cmdln.rc == 2"
  tags:
    - push-registry