
- name: "Logging in to Docker registry..."
  shell: cd {{ repo_folder }} && make docker-login
  register: cmdln
  failed_when: "cmdln.rc == 2"
  tags:
    - push-registry

- name: Tagging release images with tags latest...
  shell: cd {{ repo_folder }} && make docker-tag-latest
  register: cmdln
  failed_when: "cmdln.rc == 2"
  tags:
    - push-registry

- name: "Publishing release images to Docker Registry..."
  shell: cd {{ repo_folder }} && make docker-publish
  register: cmdln
  failed_when: "cmdln.rc == 2"
  tags:
    - push-registry

- name: Destroying build environment and Removing dangling images...
  shell: cd {{ repo_folder }} && make docker-clean
  register: cmdln
  failed_when: "cmdln.rc == 2"
  tags:
    - push-registry