
# This playbook contains docker actions that will be run on "remote" host.

- name: "Logging in to Docker registry..."
  shell: cd {{ REPO_LOCAL_PATH }} && make docker-login/{{ DOCKER_PASSWORD }}
  register: cmdln
  failed_when: "cmdln.rc == 2"
  tags:
    - publish-images
    
- name: "Publishing release images to Docker Registry..."
  shell: cd {{ REPO_LOCAL_PATH }} && make docker-publish
  register: cmdln
  failed_when: "cmdln.rc == 2"
  tags:
    - publish-images

- name: Destroying build environment and Removing dangling images...
  shell: cd {{ REPO_LOCAL_PATH }} && make docker-clean
  register: cmdln
  failed_when: "cmdln.rc == 2"
  tags:
    - publish-images